# Generated by Django 2.2.7 on 2019-11-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myplanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
