# Generated by Django 2.2.7 on 2019-11-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myplanner', '0006_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.CharField(default='annonymous', max_length=250),
        ),
    ]
