# Generated by Django 2.2.7 on 2019-11-26 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myplanner', '0008_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
