# Generated by Django 2.2.7 on 2019-11-26 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myplanner', '0012_mytask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyTask',
        ),
    ]
